/*
 * This file is generated by jOOQ.
 */
package io.seventytwo.db;


import io.seventytwo.db.tables.Customer;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>CUSTOMER</code>.
     */
    public static final Customer CUSTOMER = io.seventytwo.db.tables.Customer.CUSTOMER;
}
